name: Build Windows Executable

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Use a stable version

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pyinstaller
        pip3 install -r requirements.txt

    - name: Build executable
      run: |
        pyinstaller --onefile wcexport.py

    - name: Verify Executable
      run: |
        if not exist dist/wcexport.exe (
          echo "Executable not found!"
          exit 1
        )

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/wcexport.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
